### ISSUE TITLE
Case-sensitive comparers vs. case-insensitive comparers

### ISSUE THREAD

**Issue by joelalejandro** [prototypal/jsonapi-ts#179]
Currently, there's no way to specify if we want a case-sensitive match or not for any of the text-related comparers like `eq` or `like`.

Should we care about this? How can the behavior be expressed in a HTTP request or JSON:API operation?

**Comment by spersico** [comment]
Upon discussion with @joelalejandro, we came upon that using case insensitive is not possible using the knex `where` method, 'cause it doesn't support's that. 
A good issue to read is [this](https://github.com/tgriesser/knex/issues/233), where this is discussed, using the method `whereRaw` is recommended, and a [user comments](https://github.com/tgriesser/knex/issues/233#issuecomment-242966756) that doing this has a serious impact on perfomance, as the search will not use the indexes created for the column.

**Comment by spersico** [comment]
Upon further discussion with @joelalejandro , we arrived to the conclusion that a good approach would be to allow the user to customize the case sensitivity of a query, but that would result on the api enforcing that query somehow.
We agreed that this gets out of scope for the 1.0.0 milestone, and will revisit later.
